2019-4-5 10:06:29

In [1]:
import numpy as np

In [2]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [3]:
np.zeros([3,4])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [8]:
np.linspace(0, 10, 9).size

9

In [10]:
# 矩阵相乘
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [12]:
A * B #点乘
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [13]:
# 矩阵 +=运算符
a = np.ones((2, 3), dtype=int)

In [16]:
a += 3
a

array([[7, 7, 7],
       [7, 7, 7]])

In [15]:
a

array([[4, 4, 4],
       [4, 4, 4]])

In [18]:
a = np.random.random((2, 3))
a

array([[ 0.155551  ,  0.76425858,  0.39010035],
       [ 0.07615064,  0.49693962,  0.3975375 ]])

In [20]:
print('总和为:', a.sum())
print('平均值为:', a.mean())
print('最大值为:', a.min())
print('最小值为:', a.max())

总和为: 2.2805376898
平均值为: 0.380089614967
最大值为: 0.0761506387394
最小值为: 0.764258581199


In [23]:
# 按照某种维度
print('总和为:', a.sum(axis=1))
print('平均值为:', a.mean(axis=0))
print('最大值为:', a.min(axis=1))
print('最小值为:', a.max(axis=1))
print('累加:', a.cumsum(axis=1))

总和为: [ 1.30990993  0.97062776]
平均值为: [ 0.11585082  0.6305991   0.39381893]
最大值为: [ 0.155551    0.07615064]
最小值为: [ 0.76425858  0.49693962]
累加: [[ 0.155551    0.91980958  1.30990993]
 [ 0.07615064  0.57309026  0.97062776]]


通用函数

In [30]:
B = np.arange(3)
C = np.array([3,3,3])
print('指数:', np.exp(B))
print('sin:', np.sin(B))
print('平方:',np.sqrt(B) )
print('相加:',np.add(B, C) )
# print('cot:', )

指数: [ 1.          2.71828183  7.3890561 ]
sin: [ 0.          0.84147098  0.90929743]
平方: [ 0.          1.          1.41421356]
相加: [3 4 5]


# 索引、切片和迭代

一维数组可以被索引，切片和迭代，就像列出和其他Python序列一样。

In [31]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [45]:
print(a[2], a[1:3], a[:5:-2])

8 [1 8] [729 343]


# 多维（Multidimensional） 数组每个轴可以有一个索引。 这些索在元组中以逗号分隔给出：

In [55]:
def f(x, y):
#     y =2 
    return 10 * x + y

In [68]:
b = np.fromfunction(f, (5, 3), dtype=int)
print('b:', b)
print('第二个维度', b[1:2, 0:3])

b: [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]]
第二个维度 [[10 11 12]]


In [69]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                 [ 10, 12, 13]],
                [[100,101,102],
                 [110,112,113]]])